### ISSUE TITLE
Quiz4輸入輸出格式

### ISSUE THREAD

**Issue by botingchen** [ianchen0119/Cryptography-Engineering-2022-spring#10]
助教您好，想請問Quiz4的輸入以及輸出有甚麼規定格式嗎?

**Comment by ianchen0119** [comment]
@botingchen 
同學您好，
quiz4 的程式碼沒有規定輸入輸出格式，但是需要同學在報告中告訴我程式在解密過程如何幫助你，並且一定要使用老師上課提到的概念。

謝謝！

**Comment by botingchen** [comment]
不好意思我看到其他同學有問輸入是否為ciphertext，那我如果ciphertext直接寫死在程式碼裡面，只輸出解出來的plaintext是可以的嗎？

**Comment by ianchen0119** [comment]
@botingchen 
同學您好，
我會驗證程式碼與同學提交上來的說明文件來檢驗答案的正確性，
所以不需要特別考慮輸入的問題，只要在說明文件解釋清楚你是如何使用 data set 求解即可。

謝謝。

**Comment by TzuMinYang** [comment]
@ianchen0119 
助教您好：

　1.想問說明文件應該要寫什麼，寫程式的流程和邏輯即可嗎？

　2.有需要寫輸入輸出內容的說明嗎？

　3.如何使用data set求解的部分應該就是代投影片的公式進去算就好，這樣需要特別說明什麼嗎？

謝謝助教

**Comment by ianchen0119** [comment]
@TzuMinYang 
同學您好，

1\. 是的
2\. 大概解說一下即可
3\. 不需要，除非同學你的實作方式與投影片不同

謝謝。
