### ISSUE TITLE
Quiz4 輸入

### ISSUE THREAD

**Issue by TzuMinYang** [ianchen0119/Cryptography-Engineering-2022-spring#11]
助教您好：

　1.請問輸入是要解的密文嗎？

　2.請問在輸入時以下紅色圈起來的地方會有換行嗎？
![image](https://user-images.githubusercontent.com/30570735/159439341-1d1ab90b-9372-4bd5-90ec-ef957646484c.png)

　3.請問training set直接寫死在程式內即可嗎？

　謝謝助教。

**Comment by ianchen0119** [comment]
@TzuMinYang 
同學您好，

1\. 是
2\. 不會，你可以將密文的空格都移除方便處理
3\. 可以
