### ISSUE TITLE
Quiz 4問題

### ISSUE THREAD

**Issue by chuchunchi** [ianchen0119/Cryptography-Engineering-2022-spring#12]
助教你好：
請問我在寫程式的時候，就可以假設前三個字母是GRE嗎？

**Comment by ianchen0119** [comment]
@chuchunchi 
同學您好，
只要你的 data set 處理正確，就算不在程式中假設前三個字母是 GRE 也可以求出正解。

謝謝！

**Comment by TzuMinYang** [comment]
@ianchen0119 
助教您好：
　
　請問前兩行應該會需要假設是GR吧？第三行開始才能用投影片上的方法來計算？

謝謝助教

**Comment by ianchen0119** [comment]
@TzuMinYang 

喔喔對，實際上是這樣，不好意思！
