### ISSUE TITLE
Quiz5 Input疑問

### ISSUE THREAD

**Issue by rayray9999** [ianchen0119/Cryptography-Engineering-2022-spring#13]
助教您好：
請問題目的sample Input是直接將c606196ea460a3a53ac3e81c614b990b作為string進行MD5加密嗎？
因為我實作上直接將Input加密後的16byte MSB是c769和簡報的9cc7不一樣
但生成出來的output也同樣是c769
我將sample output加密得出來是be23也不是9cc7
因為我查到的結果是MD5加密同一個明文都是一樣的結果
想請問是不是有需要做其他調整才能和sample IO一樣

**Comment by ianchen0119** [comment]
@rayray9999 

同學您好，
試著將 input 從 hex 轉為 bytes 應該能夠解決你的問題。

謝謝！

**Comment by taylor-wu96** [comment]
助教您好：
想問input要給使用者輸入嗎？

**Comment by ianchen0119** [comment]
@a0716116z 
同學您好，
是的喔，E3 公告有提到：
> Note: Submitted program will need to read the message from stdin and output the result followed by a newline to stdout.

謝謝！
