### ISSUE TITLE
找collision

### ISSUE THREAD

**Issue by BaCHiiii** [ianchen0119/Cryptography-Engineering-2022-spring#14]
不好意思，請問助教，通常都怎麼找這段明文的collision?hashlib有可以用的函式嗎?我不太知道怎麼找。

**Comment by ianchen0119** [comment]
@BaCHiiii

同學您好，

hashlib 只提供 md5 hash 這個部分的功能，至於**如何找到與輸入碰撞的資料**就是同學需要去思考的問題了，
所以針對這個問題我沒有辦法給你提示，不好意思！

**Comment by BaCHiiii** [comment]
好的，謝謝助教

**Comment by BaCHiiii** [comment]
請問助教，collision是隨便找一個都可以嗎?

**Comment by ianchen0119** [comment]
@BaCHiiii 
同學您好，是的喔！
