### ISSUE TITLE
關於 Quiz 5 Bonus & Critique1

### ISSUE THREAD

**Issue by grey404nf** [ianchen0119/Cryptography-Engineering-2022-spring#15]
1. 請問 Quiz 5的Bonus 要以何種形式繳交? 是以 學號.pdf 連同quiz 5的py檔壓成zip即可嗎?
2. 請問 E3的Critique1 是上周課堂上說期限延至春假後的那個嗎? 如果是的話, 那期限是E3說的05/05嗎, 或是打錯?

**Comment by ianchen0119** [comment]
@grey404nf 
同學您好
1. 請先以學號命名存成 pdf 一同打包，謝謝！
2. 是的，日期為助教誤植，我晚點會把時間改回來。
