### ISSUE TITLE
Lecture5 投影片問題

### ISSUE THREAD

**Issue by TzuMinYang** [ianchen0119/Cryptography-Engineering-2022-spring#17]
助教您好：

　請問Lecture5 p53 圈起來的這邊是不是有打錯？應該是r^n？
![image](https://user-images.githubusercontent.com/30570735/160545930-fc89165f-7705-42a7-83a5-d39b09cdc74d.png)

 　謝謝。

**Comment by ianchen0119** [comment]
@TzuMinYang 
同學您好，
跟老師確認後確定是投影片有誤，
我這邊會幫你記錄一下額外加分，

謝謝！
