### ISSUE TITLE
Quiz6 公式疑問

### ISSUE THREAD

**Issue by taylor-wu96** [ianchen0119/Cryptography-Engineering-2022-spring#18]
1.作業講義上提到的R(B1,B2)的Fx(B1,B2)次方進行聯乘，是要將每個出現在R(B1,B2)裡面有頻率的數字都計算一遍嗎？即便相對應的Fx(B1,B2)出現頻率是0次？
2.老師上課說要使用Trigram的方式處理，但助教用的方式是直接解碼，將頻率乘上頻率的次方，請問區別在哪裡，感覺沒有使用到條件機率的部分？
3.Fx(B1,B2)是將原本的密文經過現在的鑰匙解密之後得到的明文頻率計數嗎？ 另外想問Fx(B1,B2)裏面B1，B2表示的是一個字母，假設B1代表A，B2代表B，那麼Fx(B1,B2)指的是在還原的明文中，AB出現的頻率嗎？還是是條件機率 A後面出現AB的機率呢？
4.在算R(B1,B2)的Fx(B1,B2)次方進行聯乘時候，是否要轉成對數進行運算
5.是否要紀錄哪些key是已經被拋棄的？
<img width="409" alt="image" src="https://user-images.githubusercontent.com/65119444/162477656-bee419b4-ccd0-4bd3-a685-8ae7b69f7dab.png">

**Comment by KWChen1997** [comment]
1. 建議示意開始就把R(B1,B2)都算過，之後在算score的時候對有出現的項目算次方就好 (也可以用log去算)
2. 我的方法是用bigram，不是trigram所以可能跟老師上課說的不太一樣
3. Fx(B1,B2)的B1,B2是指用x解密後的明文中B1B2出現的頻率
4. 對數跟指數都可以，但建議用log去運算會比較好
5. 不需要紀錄也可以

**Comment by taylor-wu96** [comment]
請問助教會出現overflow怎麼辦？每一次跑分數都會overflow
