### ISSUE TITLE
有時候會跑出來的問題

### ISSUE THREAD

**Issue by BaCHiiii** [ianchen0119/Cryptography-Engineering-2022-spring#20]
![image](https://user-images.githubusercontent.com/100584575/162607873-cde856e8-cd06-4bbd-a262-329311d31228.png)
請問這個在跑的時候有時候會報錯，但有時候又不會，請問是甚麼問題呢?有關係嗎?

**Comment by ianchen0119** [comment]
@BaCHiiii 
同學您好，
請參考 [Python: OverflowError: math range error](https://stackoverflow.com/questions/4050907/python-overflowerror-math-range-error)，應該會對你有幫助！

**Comment by BaCHiiii** [comment]
所以我可以改template嗎? 這樣看起來會改到

**Comment by ianchen0119** [comment]
@BaCHiiii 
同學您好，
在不影響程式輸出結果的清況下沒問題。

**Comment by TzuMinYang** [comment]
@ianchen0119 
助教您好，請問可以import numpy as np嗎？
我在我的虛擬機import時，使用$ ./test.py去執行程式會報錯說沒有安裝numpy，但如果我用$ python3 test.py即可正常執行
後來執行$ sudo apt-get install python-numpy後就沒問題了
所以先想確認在助教測試的環境我們可以import numpy as np嗎？

**Comment by KWChen1997** [comment]
同學你好，
numpy是可以使用的
