### ISSUE TITLE
Berkelamp-Massey 算法問題

### ISSUE THREAD

**Issue by brianchennn** [ianchen0119/Cryptography-Engineering-2022-spring#22]
![image](https://user-images.githubusercontent.com/46628572/163871977-1825fcb3-ca88-4255-8cd0-e2ded7eaf626.png)

不好意思 可能是我離散沒學好 但為甚麼這裡餘式的degree會等於除式的degree ? 正常的長除法不會得出這樣的結果吧 ?

**Comment by ianchen0119** [comment]
@brianchennn 
同學您好，
可以請問一下這是哪一份投影片的第幾頁嗎？
謝謝。

**Comment by brianchennn** [comment]
@ianchen0119 Lecture 7 April 11 2022 (Week 7) April 15 0930  page 13
以及 Berlekamp Massey Algorithm April 9 2022 1330 page 7

**Comment by ianchen0119** [comment]
@brianchennn 
同學您好，

這些算式都是以 GF(2) 下去計算的，你可以將兩者的每一項對齊後做按位元逐一做 OR 運算，像是這樣：
<img width="446" alt="image" src="https://user-images.githubusercontent.com/42661015/163948204-17c50a52-554b-4509-b471-af473bcc5199.png">

- [Ref](https://en.wikipedia.org/wiki/GF(2))

**Comment by brianchennn** [comment]
@ianchen0119 所以這並不是單純的xor長除法運算 而是將除式left shift到對齊被除式之後 再進行xor長除法運算 所以商只有一項 這樣理解沒問題嗎?
那為甚麼 page 4 的餘式又會跑出大於一項的商呢?
![image](https://user-images.githubusercontent.com/46628572/163978534-d387d4fd-32d3-49c3-97e3-494e6a4cf53e.png)

**Comment by ianchen0119** [comment]
@brianchennn 
同學您好，
商不一定只會有一項，第 i 步的商會是第 i - 2 步的 GCD 除以第 i - 1 步的 GCD，所以 `X^8+X^4+X^3+X+1 / X^4+X^3+X+1` 會得到 `X^4+X^3+X^2+1`，算法可以參考這個[影片](https://www.youtube.com/watch?v=ApIFldw-Hpw)，謝謝！

> 題外話：我覺得 [wikipedia](https://zh.wikipedia.org/wiki/%E6%89%A9%E5%B1%95%E6%AC%A7%E5%87%A0%E9%87%8C%E5%BE%97%E7%AE%97%E6%B3%95) 上的定義比較清楚，或許同學可以參考看看！

**Comment by brianchennn** [comment]
@ianchen0119 可是為什麼這張圖的除式是7,6,2次方的係數為1？
明明講義是寫 x^6 + x^5 + x 應該是 6,5,1 吧 怎麼自動left shift變成 7,6,2 了？
![](https://user-images.githubusercontent.com/42661015/163948204-17c50a52-554b-4509-b471-af473bcc5199.png)

![](https://user-images.githubusercontent.com/46628572/163871977-1825fcb3-ca88-4255-8cd0-e2ded7eaf626.png)

**Comment by kirito878** [comment]
後面還有乘一個X吧

**Comment by brianchennn** [comment]
@kirito878 那為什麼餘式degree會跟除式一樣大? 商為甚麼是x 而不是x+1 ?
我下面這樣算會有什麼問題嗎？
![image](https://user-images.githubusercontent.com/46628572/164027201-741bf38f-193e-4de4-b52a-0244e6359d4e.jpeg)

**Comment by ianchen0119** [comment]
@brianchennn 
同學您好，
可以參考我在前面提供給你的影片連結，影片有提到 Polynomial Division in GF(2) 的計算方式，如果你使用這個方式就能推導出跟投影片上一樣的結果了！

**Comment by TzuMinYang** [comment]
@ianchen0119 
助教您好，我和提問題的同學有一樣的問題，為什麼商不能是x+1呢？
我上網找了一個GF(2)的計算機，我有拿投影片的式子來驗證一下，這個計算機應該是正常的
但對於這題，我用這個計算機算出來的結果商也同樣是x+1
![image](https://user-images.githubusercontent.com/30570735/164171122-53036bad-03bc-4532-b1c6-dadf9559cf06.png)

計算機連結：http://www.ee.unb.ca/cgi-bin/tervo/calc.pl?num=10110001&den=1100001&f=d&e=1&p=1&m=1
謝謝助教

**Comment by kirito878** [comment]
![image](https://user-images.githubusercontent.com/101275165/164182023-7e608787-382e-49c1-bfad-2966f64a1071.png)
投影片中把那個1放在了下一次的計算中，不過具體來說為什麼要這樣就不知道了

**Comment by ianchen0119** [comment]
@TzuMinYang & @brianchennn 
就跟 @kirito878 所說的一樣，老師將 x + 1 拆成兩個部分去做講解，具體的原因我跟老師討論一下再答覆你們，
大家辛苦了！
