### ISSUE TITLE
Quiz7 請問可以使用 galois 這個 module嗎？

### ISSUE THREAD

**Issue by TzuMinYang** [ianchen0119/Cryptography-Engineering-2022-spring#23]
@ianchen0119 助教您好：

　1.想請問quiz7 q1可以使用 galois 這個 module嗎？ https://galois.readthedocs.io/en/v0.0.26/index.html

　2.請問quiz7 q3有定義在GF(?)之下嗎？ 還是就用一般的除法去算就好？

謝謝助教。

**Comment by ianchen0119** [comment]
@TzuMinYang 
同學您好，
1\. Yes
2\. 可以按照投影片使用的 GF(2) 下去實作，如果同學有其他更好的方法那也沒有問題。

謝謝

**Comment by TzuMinYang** [comment]
@ianchen0119 
助教您好：

> 2. 可以按照投影片使用的 GF(2) 下去實作，如果同學有其他更好的方法那也沒有問題。

　可是他的係數是0, 1, 1, 2, 3, 5, 8, 13, 21, 34，在GF(2)的話係數不是應該只有0或1嗎？
　所以我才想說是不是要自己幫他定義說是在GF(?)底下運算？
　或是我的理解哪裡有問題呢？

謝謝助教。

**Comment by TzuMinYang** [comment]
@ianchen0119 
助教您好：

想再請問另一個問題，如果用教授教的modified Berlekamp-Massey algorithm的話，做extened Euclidean algotithm做到停止那時的B(x)就是modified Berlekamp-Massey algorithm的答案嗎？

如果用投影片的範例的話做extened Euclidean algotithm做到停止那時的B(x)的確就是modified Berlekamp-Massey algorithm的答案，但我再多試其他例子就錯了，所以想請問助教做完extened Euclidean algotithm後還要再做什麼運算才是modified Berlekamp-Massey algorithm的答案呢？

我看投影片看了滿久還是看不懂接下來應該要怎麼做，上網查也都是找到一般版的Berlekamp-Massey algorithm。

----------------------------------------------------------------

我後來發現在input長度是2的倍數時，做extened Euclidean algotithm做到停止那時的B(x)就是modified Berlekamp-Massey algorithm的答案，長度不是2的倍數時答案就會有問題，想請問這是為什麼？
我在這篇論文有看到類似的演算法 http://hlombardi.free.fr/publis/BMAvar.pdf

謝謝助教。

**Comment by brianchennn** [comment]
> @ianchen0119 助教您好：
> 
> > 2. 可以按照投影片使用的 GF(2) 下去實作，如果同學有其他更好的方法那也沒有問題。
> 
> 　可是他的係數是0, 1, 1, 2, 3, 5, 8, 13, 21, 34，在GF(2)的話係數不是應該只有0或1嗎？ 　所以我才想說是不是要自己幫他定義說是在GF(?)底下運算？ 　或是我的理解哪裡有問題呢？
> 
> 謝謝助教。

我也跟這位同學一樣，不懂該如何用GF(2)去算Fibonachi的特徵多項式，請助教在截止期限前給點題示。

**Comment by ianchen0119** [comment]
@TzuMinYang 
@brianchennn 
同學您好，
抱歉助教昨天搞錯了，請你們把他們當作一般多項式用十進制去除即可，不好意思🙏

**Comment by ianchen0119** [comment]
@TzuMinYang 
> 想再請問另一個問題，如果用教授教的modified Berlekamp-Massey algorithm的話，做extened Euclidean algotithm做到停止那時的B(x)就是modified Berlekamp-Massey algorithm的答案嗎？

是的，做到那邊停止時 B(x) 就是答案。

> 我後來發現在input長度是2的倍數時，做extened Euclidean algotithm做到停止那時的B(x)就是modified Berlekamp-Massey algorithm的答案，長度不是2的倍數時答案就會有問題，想請問這是為什麼？

這個我向老師確認以後再回覆您！
