### ISSUE TITLE
投影片 Lecture 7 p4 error

### ISSUE THREAD

**Issue by TzuMinYang** [ianchen0119/Cryptography-Engineering-2022-spring#25]
助教您好：

　這邊GCD(56,16)應該是GCD(56,15)才對？ 因為後面的範例都是做GCD(56,15)
![image](https://user-images.githubusercontent.com/30570735/164766226-4b8e44cf-51f7-451f-91f9-9807ddfc0690.png)

謝謝助教

**Comment by ianchen0119** [comment]
同學您好，

感謝您的回報！
