### ISSUE TITLE
Midterm Problem 2 Z*p 

### ISSUE THREAD

**Issue by brianchennn** [ianchen0119/Cryptography-Engineering-2022-spring#26]
助教 請問Z<sup>*</sup><sub>p</sub>是繼承自Problem 1的敘述嗎？

**Comment by hungdino** [comment]
助教好，
我在這邊 Echo Brian：Problem 2 題幹沒有提到 Z*p 的定義，是否是使用 Problem 1 的定義？
如果是的話，第二題的第二行「The seed is a value x0」和第三個子題「How many output bits S = x0, x1, x2...」，兩者哪一個描述比較準確，也就是說 x0, x1 的 Value 是 integer 或是 binary？

**Comment by KWChen1997** [comment]
同學們好，題目1,2的Z*p是一樣的
由於數學中大寫Z的集合通常代表整數，所以沒有特別描述。
關於第二題的描述，x0是integer

謝謝你們的提醒
