### ISSUE TITLE
Midterm Problem 7

### ISSUE THREAD

**Issue by brianchennn** [ianchen0119/Cryptography-Engineering-2022-spring#27]
助教 請問
(b) 的"small than 2<sup>l</sup>"有什麼意義呢？我搞不太懂這題要問什麼

**Comment by hungdino** [comment]
Echo Brain：原文是 Smaller that，但若以比較級看得話，應該是 smaller than，但即便是 smaller than，2^l 也是相當大的範圍，這樣的限制有什麼含義嗎？

**Comment by KWChen1997** [comment]
同學你好，
smaller that是我的typo，應該是"smaller than"，謝謝你的更正。
關於smaller than 2^l的意義跟下一句有關係，你們可以再想一下。
