### ISSUE TITLE
midterm7(a)

### ISSUE THREAD

**Issue by ghost** [ianchen0119/Cryptography-Engineering-2022-spring#29]
助教好，
我想請問
The idea is to ask for the MACs of. The idea is to ask for the MACs of. two messages of length l and construct them from the MAC of a message of length 2l. two messages of length l and construct them from the MAC of a message of length 2l.
這句話是甚麼意思?
因為ask for 後面好像沒有寫要求，最後一句and前面也沒有動詞
謝謝助教~

**Comment by KWChen1997** [comment]
同學你好，你可能有不小心編輯到word檔，麻煩你重新下載一次。
