### ISSUE TITLE
Quiz3 P.10與P.35, P.36 index方法不一致

### ISSUE THREAD

**Issue by cschang810** [ianchen0119/Cryptography-Engineering-2022-spring#3]
_Quiz 3 Spring 2022 March 6.pdf_

**P.10的index從1開始**
```
C(3) + W(23) = Z(26)
```

**P.35, P.36的index從0開始**
```
J(9) + A(0) = J(9)
```

作業是zero-indexed

**Comment by ianchen0119** [comment]
同學好，

感謝您的回報，這邊再請你留下學號，老師之後會依情況幫你加分，謝謝！

**Comment by cschang810** [comment]
學號: 309551128
感謝!
