### ISSUE TITLE
Midterm Problem 1 第一小題 證明程度

### ISSUE THREAD

**Issue by hungdino** [ianchen0119/Cryptography-Engineering-2022-spring#30]
助教您好，

請問 Midterm Problem 1 第一小題提到「Prove that this cipher provides perfect secrecy」，但我的理解是上課只有學到兩三個 criteria，請問這題是只需要依照上課學到的 criteria 進行說明，還是需要較為嚴謹的數學證明？

**Comment by KWChen1997** [comment]
同學你好，
只要證明到上課學到的程度即可
