### ISSUE TITLE
期末提案繳交區

### ISSUE THREAD

**Issue by ianchen0119** [ianchen0119/Cryptography-Engineering-2022-spring#33]
各位同學好，

請你們按照下方的留言格式留言以繳交期末提案：
```
## 組員
- 310550000
## {題目名稱}
- 提案影片連結
```

謝謝！

**Comment by ianchen0119** [comment]
## 組員
- 310551012
- 310555018
- 310551159
## 題目：XOR Filter 介紹
- [影片連結](https://drive.google.com/file/d/1AFtfQIhe7P4r1F9iJqO6hASpxu9wiXSF/view?usp=sharing)

**Comment by bwyanyuuu** [comment]
## 組員
- 0716015
- 0716239
- 0716302
- 0716326
## DNA cryptography
- [提案影片連結](https://drive.google.com/file/d/1FOvD4VpqfBrNIRsj1FX3fN4ACqdhvpwb/view?usp=sharing)

**Comment by jimmywang0913** [comment]
0716029
0716083
0716081
0716065

## REEEEAL RAMDOM SEED
[https://drive.google.com/file/d/1dWvyLko-SJ8VM86ciU0B0OGcbTpvN1CT/view?usp=sharing](url)

**Comment by ashuantw** [comment]
## 組員
- 0816054
- 0816016
## Zero Knowledge Protocol
- [提案影片連結](https://drive.google.com/file/d/1KeiQI3UbHcuoefYoExU_4At2lwbyrLis/view?usp=sharing)

**Comment by liitiisu** [comment]
## 組員
- 310553011
- 310553016
## Honey Encryption for Natural Language
- [影片連結](https://drive.google.com/file/d/1Ftc9vwfCPsyoqQWwh6H7dyMCnZztfJQ7/view?usp=sharing)

**Comment by Hanson-Tsai** [comment]
## 組員

- 310552030
- 310552038
- 310555004

## Network Layer Hijacking

- [影片連結](https://www.youtube.com/watch?v=VcP_-W6acJI)

**Comment by ghost** [comment]
### 組員

- 0716211

- 0713211

- 0716225

- 0717030

###  題目: grapic encryption

- https://drive.google.com/file/d/1QSBsnBw7MqdV2lWh0iiXFUwE_5TrUBBD/view?usp=sharing

**Comment by jejewu** [comment]
組員

- 310552053

- 310552032

- 310551030

- 310553001

- 0716018

題目: Secure Voting
- [網址](https://drive.google.com/file/d/1OQvJTVnX9oJOwEx15OF3IGwojzHujVD-/view?usp=sharing)

**Comment by JianShuiHuang** [comment]
## 組員

- 0716064
- 0716304
- 0716330
- 0713223

## DNA Cryptography

- [提案影片連結](https://drive.google.com/file/d/13_SUirZpZSndcbYp4SK4MB27inEpOlvf/view?usp=sharing)

**Comment by grant6301** [comment]
## 組員
- 510557023
## Fully Homomorphic Encryption
- [提案影片連結](https://nycu1-my.sharepoint.com/:v:/g/personal/grant6301_c_m365_nycu_edu_tw/ESC4biEMyuFFguUzan3gLtMBINRzbNJnIS7dizxUaLY5LA?e=31udAb)

**Comment by Alonza0314** [comment]
### 組員
109550096
109550161
109550014
109550130
### DNA Cryptography
[https://drive.google.com/file/d/10mgrPgcuXHI_UkwWsDQ-VrrrLoocOdTi/view?usp=sharing](url)

**Comment by taylor-wu96** [comment]
組員
0816088
0816089
0716116
0616041

**### Audio encryption**

[影片連結](https://drive.google.com/file/d/13fC99WQb38RTkbBSld83twiKbqkLa4jr/view?usp=sharing)

**Comment by HsiaoE** [comment]
## 組員
- 0711099
- 0716242
- 0812501
## Honey encryption
- [提案影片連結](https://www.youtube.com/watch?v=YgZCz5BVTh4)

**Comment by chungmin-yu** [comment]
## 組員
- 0716236
- 0716221
- 0716202
- 0716045
## Functional Encryption
- [提案影片連結](https://drive.google.com/file/d/1Yr9tuqRer0twQ0Auy_fhq0kiitDrMVWg/view?usp=sharing)

**Comment by BaCHiiii** [comment]
### 組員

0816170
0816169
0816021
0816045
0816101
### Honey encryption
https://drive.google.com/file/d/1qWyYaP29_OOSfbutg_kxArq5fQ1k7laL/view?usp=sharing

**Comment by ohsuo11** [comment]
## 組員
- 0816015
## Comparing algorithms: AES-256 GSM, ChaCha20-Poly1305, NIST Light Weight Encryption and NSA Simon, Speck Cipher
- [提案影片連結](https://drive.google.com/file/d/1yxevlXxXpoEjcmoAzLKliVNJSRK-zdH-/view?usp=sharing)

**Comment by rayray9999** [comment]
### 組員
- 109550155
- 109550079

### ZIP Password Cracker
[影片連結](https://drive.google.com/file/d/15lBvkyB1HjtzqH9HCSkVUhkxrIzborbY/view)

**Comment by cschang810** [comment]
## 組員
- 309551128
## Lightweight Cryptography
- [提案影片連結](https://drive.google.com/file/d/1pzT5SjoK0Kln-tIegeSW2sJSPMIcdsBO/view?usp=sharing)

**Comment by lon5948** [comment]
## 組員
- 109550005
- 109550025
- 109550027
- 109550031
- 109550118
## Secure Voting
- [連結](https://drive.google.com/file/d/1aJ7eUYB6Bi8mNZA5xANjZ5lmv0AMOisn/view?usp=sharing)

**Comment by eliawang2000** [comment]
## 組員
- b102532
- 0716002
- 0716008
- 0716052
- 0716056
## DNA Cryptography
- [影片連結](https://drive.google.com/file/d/11ZAIa5Hr-7t_vnsGbfUqE2GUB0UkC0_Y/view?usp=sharing)

**Comment by alan890104** [comment]
## 組員

- 0716235
- 0716046
- 0716074
- 0716055
- 0716063

## Smart Ponzi Scheme
- [提案影片連結](https://drive.google.com/file/d/18TVzLHQMlGFIuFg27Jnu-hf4_T4dyRqK/view?usp=sharing)

**Comment by HengKuu** [comment]
## 組員
- A101107
## Homomorphic encryption on simple machine learning tasks
- [影片連結](https://drive.google.com/drive/u/0/folders/1136rWU968Ci2-ZqScrrPfargWxOYWoWp)

**Comment by Wachemanston** [comment]
## 組員
- 310552024
## Merkle Tree
- [影片連結](https://drive.google.com/file/d/14NDqVAa7AnuRkpq3_6ZwfBNBrUezpidS/view?usp=sharing)

**Comment by syc0415** [comment]
## 組員
- 109550165
- 109550087
## An Improved AES S-box
- [影片連結](https://youtu.be/xrDgzjq2tmo)

**Comment by TrashBoatDora** [comment]
## 組員
- 109550048
- 0716247
## 區塊練模擬
- [提案連結](https://drive.google.com/file/d/1Xx2syPvCv7ltBukrz_heBbRTtpsHYfY2/view?usp=sharing)

**Comment by rayzhou0511** [comment]
### 組員

- 0713331
- 0713312

### Honey encryption

- [提案連結](https://drive.google.com/file/d/1ntAqlXUNUQ2vCjpCL3WkDTa8KfD2SzoB/view)

**Comment by YourName0729** [comment]
## 組員
- 0712211
- 0712254
## Homomorphic Encryption from Learning with Errors
- https://drive.google.com/file/d/1NH2MAupNHPiNEzFhZWtXh0q3wib4YWw9/view?usp=sharing

**Comment by MinChihHsu** [comment]
## 組員
- 109550137
## Small Scale Variants of the AES
- [提案影片連結](https://drive.google.com/file/d/1-ps-T1BW7V2vSwMgfrb_7X-uf-DaH5ho/view?usp=sharing)

**Comment by TzuMinYang** [comment]
## 組員
- 0816147 楊子民
- 0816104 涂志瑋

## ZIP password cracker - plaintext attack
- [提案影片連結](https://drive.google.com/file/d/1dEj2aHwbacuHyaYEu99DNrJuXPlcc6cb/view?usp=sharing)

**Comment by grey404nf** [comment]
## 組員
- 0813367
## Cryptography in Cryptocurrency
- [提案影片連結](https://drive.google.com/file/d/1d8uKtTWLcleAWHjBqtqB_Muxi82UPpQ4/view?usp=sharing)

**Comment by patrick0330** [comment]
## 組員

- 0716324

- 0812102

- 0716320
## ZIP Password Cracker

- [提案影片](https://drive.google.com/file/d/1CDAUtUMixwaLH7eu9xDRmLtL1sr49I7W/view?usp=sharing)

**Comment by jash4088** [comment]
## 組員
- 309551149
## Simple TRNG on my desk
- [提案影片連結](https://drive.google.com/file/d/13mz3yWPiqgdXWaO63qp446I_lO4OjB9A/view)

**Comment by abt8601** [comment]
## 組員
- 310551038
## Lightweight Encryption – Performance Benchmark on Microcontroller
- [https://drive.google.com/file/d/1Py2BENMugIsD861vZwov8GM-a1KQR8ea/view?usp=sharing](https://drive.google.com/file/d/1Py2BENMugIsD861vZwov8GM-a1KQR8ea/view?usp=sharing)

**Comment by richardshiue** [comment]
## 組員
- 0186156
- 0816158
## AES S-Box Design 
- [提案影片連結](https://drive.google.com/file/d/1LuJZ896uwtWxNVNbbaurZNfxRvN25XlP/view?usp=sharing)

**Comment by txmmoon19** [comment]
組員

0616046

題目
Honey encryption

https://drive.google.com/drive/folders/1-6fy5ItXINDYjYvRv2pRrkXJ5vPdGAwI

**Comment by ianchen0119** [comment]
===繳交截止===

**Comment by ianchen0119** [comment]
@txmmoon19 
@abt8601 
@JianShuiHuang 
同學們好，

請將分享的連結資源設為所有人都能存取喔，
謝謝！

**Comment by abt8601** [comment]
> 請將分享的連結資源設為所有人都能存取喔， 謝謝！

已修正，感謝提醒。

**Comment by txmmoon** [comment]
助教抱歉，之前沒有看到，已經修正了，不好意思!
