### ISSUE TITLE
Midterm Problem 8

### ISSUE THREAD

**Issue by ywliu722** [ianchen0119/Cryptography-Engineering-2022-spring#35]
助教好 因為這題有點不知道要怎麼開始解題
所以想跟助教討論一下目前遇到的一些疑問
1. 題目有說到key的最大長度不超過32 是不是代表LFSR的最大長度為5 (2^5 = 32)
2. 如果在不知道部分key 或是 部分plaintext來算出key 的狀況下，要怎麼使用Berlekamp-Massay algorithm來找出LFSR的長度
3. 換句話說，在題目中我們知道initial seed以及可能的LFSR長度，那是不是就可以用得出的key直接解密密文，不用使用Berlekamp-Massay algorithm呢
4. 題目提到的CVSD對於解題有什麼樣的用處嗎

**Comment by TzuMinYang** [comment]
助教好：

　1.請問我們要怎麼知道第八題原本的plaintext哪邊是silence的？
　　因為教授說的對ciphertext shift後和原本的ciphertext 做XOR的方法應該要知道哪邊是silence哪邊是speech才行？

　2.請問就算我們知道哪邊是silence的，XOR完取出來的亂數應該也是a'[i] = a[i] XOR a[i+1]？但我們的Berlekamp-Massey algorithm有辦法用a'解出a嗎？

　3.請問我看我的ciphertext.bin只有510bytes，也就是4080bits是正常的嗎？我看考卷上是說會有4096bits

謝謝助教

**Comment by KWChen1997** [comment]
> 助教好 因為這題有點不知道要怎麼開始解題 所以想跟助教討論一下目前遇到的一些疑問
> 
>     1. 題目有說到key的最大長度不超過32 是不是代表LFSR的最大長度為5 (2^5 = 32)
> 
>     2. 如果在不知道部分key 或是 部分plaintext來算出key 的狀況下，要怎麼使用Berlekamp-Massay algorithm來找出LFSR的長度
> 
>     3. 換句話說，在題目中我們知道initial seed以及可能的LFSR長度，那是不是就可以用得出的key直接解密密文，不用使用Berlekamp-Massay algorithm呢
> 
>     4. 題目提到的CVSD對於解題有什麼樣的用處嗎

1. 題目並沒有說key的最大長度是32 而是lfsr的長度最大為32bit
2. Berlekamp-Massay algorithm不需要知道長度
3. 這個問題應該是因為你誤解了題目的意思
4. CVSD是一個實際的案例也就是這題目的編碼方式，他的編碼方式也是一個解題的關鍵

**Comment by KWChen1997** [comment]
> 助教好：
> 
> 　1.請問我們要怎麼知道第八題原本的plaintext哪邊是silence的？ 　　因為教授說的對ciphertext shift後和原本的ciphertext 做XOR的方法應該要知道哪邊是silence哪邊是speech才行？
> 
> 　2.請問就算我們知道哪邊是silence的，XOR完取出來的亂數應該也是a'[i] = a[i] XOR a[i+1]？但我們的Berlekamp-Massey algorithm有辦法用a'解出a嗎？
> 
> 　3.請問我看我的ciphertext.bin只有510bytes，也就是4080bits是正常的嗎？我看考卷上是說會有4096bits
> 
> 謝謝助教

1. 這個要麻煩你自行研究
2. 可以，這也是老師希望你們解的問題之一
3. 我儲存的問題，請在前方補2bytes的0，謝謝你的提醒

**Comment by TzuMinYang** [comment]
@KWChen1997 助教好：

> 我儲存的問題，請在前方補2bytes的0，謝謝你的提醒

　1. 請問我要在程式補0還是在ciphertext.bin補0呢？
　也就是助教在測試我們程式的檔案會是跟現在我們使用的一樣還是會是補0之後的檔案？

　2.請問程式有限制時間嗎？我的會跑大約23秒

謝謝助教

**Comment by KWChen1997** [comment]
> @KWChen1997 助教好：
> 
> > 我儲存的問題，請在前方補2bytes的0，謝謝你的提醒
> 
> 　1. 請問我要在程式補0還是在ciphertext.bin補0呢？ 　也就是助教在測試我們程式的檔案會是跟現在我們使用的一樣還是會是補0之後的檔案？
> 
> 　2.請問程式有限制時間嗎？我的會跑大約23秒
> 
> 謝謝助教

1. 我在e3上已經更新了 你可以下載新的版本
2. 不會有太嚴格的時間限制，不要跑半小時還跑不出來應該都還可以接受(我的版本是berlekamp-massey跑大約4000次 基本上執行不需要到1秒鐘 你可以參考看看)

**Comment by TzuMinYang** [comment]
@KWChen1997 助教好：
　
> 不會有太嚴格的時間限制，不要跑半小時還跑不出來應該都還可以接受(我的版本是berlekamp-massey跑大約4000次 基本上執行不需要到1秒鐘 你可以參考看看)

　1.我的berlekamp-massey是用上次quiz7自己寫的，所以跑比較慢，我剛剛換成網路上的berlekamp-massey就不到1秒就好了。只是網路上找到的方式都和教授上課教的不太一樣。

　助教說不要跑太久都還跑不出來就好，那我應該還是用自己寫的berlekamp-massey。想確認能不能和上次quiz7一樣使用galois 這個 module？quiz7時說可以 https://github.com/ianchen0119/Cryptography-Engineering-2022-spring/issues/23


　3.請問第八題交程式碼即可嗎？還是需要有說明？

　4.繳交的檔案中好像沒有提到需要程式碼？
![image](https://user-images.githubusercontent.com/30570735/166474823-786cab1b-8628-480f-9b82-ae3483debbdf.png)

　5.請問助教是只看答案嗎？還是就算答案有錯也是會看程式碼內容，有一些概念對就有部分給分？

謝謝助教

**Comment by rayray9999** [comment]
助教您好：
請問Hint3的部分是老師提示lfsr的長度是兩者之一嗎？
而您上面提到說Hint2是指lfsr最大是32
因為如果我沒理解錯的話，Hint3好像讓Hint2顯得沒有額外意義

另外想請問一下，Hint3說initial seed是1是表示能確定LFSR最前面序列的數字是1還是代表是001or00001呢？
謝謝您

**Comment by KWChen1997** [comment]
> @KWChen1997 助教好： 　
> 
> > 不會有太嚴格的時間限制，不要跑半小時還跑不出來應該都還可以接受(我的版本是berlekamp-massey跑大約4000次 基本上執行不需要到1秒鐘 你可以參考看看)
> 
> 　1.我的berlekamp-massey是用上次quiz7自己寫的，所以跑比較慢，我剛剛換成網路上的berlekamp-massey就不到1秒就好了。只是網路上找到的方式都和教授上課教的不太一樣。
> 
> 　助教說不要跑太久都還跑不出來就好，那我應該還是用自己寫的berlekamp-massey。想確認能不能和上次quiz7一樣使用galois 這個 module？quiz7時說可以 #23
> 
> 　3.請問第八題交程式碼即可嗎？還是需要有說明？
> 
> 　4.繳交的檔案中好像沒有提到需要程式碼？ ![image](https://user-images.githubusercontent.com/30570735/166474823-786cab1b-8628-480f-9b82-ae3483debbdf.png)
> 
> 　5.請問助教是只看答案嗎？還是就算答案有錯也是會看程式碼內容，有一些概念對就有部分給分？
> 
> 謝謝助教

1. 可以和quiz7 一樣用galois去解
3. 繳交程式碼即可
4. 檔案名稱麻煩幫我取名為"學號_p8.py"
5. 會部份給分

**Comment by KWChen1997** [comment]
> 助教您好： 請問Hint3的部分是老師提示lfsr的長度是兩者之一嗎？ 而您上面提到說Hint2是指lfsr最大是32 因為如果我沒理解錯的話，Hint3好像讓Hint2顯得沒有額外意義
> 
> 另外想請問一下，Hint3說initial seed是1是表示能確定LFSR最前面序列的數字是1還是代表是001or00001呢？ 謝謝您

lfsr最大長度為32不代表長度一定為32，可能不到32
initial seed是1代表是001or00001
