### ISSUE TITLE
Quiz 3 程式數量問題

### ISSUE THREAD

**Issue by denny3388** [ianchen0119/Cryptography-Engineering-2022-spring#5]
助教您好：
所以我們應該是要將 p.2 的三個小題寫在三個不同程式裡面嗎？
因為我看 e3 上的檔名範例只有到 Q2，所以想說確認一下～

**Comment by ianchen0119** [comment]
同學您好，

應該只會需要寫兩隻程式才對：
1. 透過密文推導出 Key Length
2. 使用推導出的 Key Length + 密文求出 Key

如果還有什麼問題歡迎在下方提出，謝謝。

**Comment by BaCHiiii** [comment]
助教好，請問是一定要寫兩支程式嗎?還是只需要用jupyter分區段就可以了?謝謝助教

**Comment by ianchen0119** [comment]
@BaCHiiii 
同學您好，建議參考以下格式繳交：
```
310551012 

    |-- 310551012_q1.py 

    |-- 310551012_q2.py

    |-- 310551012_msg1.txt

    |-- 310551012_msg2.txt

    |-- 310551012_msg3.txt
```

謝謝！
