### ISSUE TITLE
Quiz3 q2要先重複做一次q1的內容然後再輸出解密後的明文嗎？

### ISSUE THREAD

**Issue by TzuMinYang** [ianchen0119/Cryptography-Engineering-2022-spring#7]
助教您好：

　1.quiz3 q1是要找出密鑰長度並輸出，q2要解密輸出明文。而q2要解密也同樣需要先算出密鑰長度，又看到助教說兩個程式input都只有密文，那這樣q2的程式內容是不是就要先重複一次q1的程式內容，找出密鑰長度後再繼續解密？
　因為q2重複做了和q1一樣的事情所以有點疑惑。

　2.想請問quiz3的這頁投影片是什麼意思？ 
　fi是代表密文中字母的出現次數嗎？fi'、k和N'是代表什麼呢？
　並且這一頁的IC公式跟quiz2的公式好像不太一樣，請問差別在哪裡？這頁算出來的是代表什麼意思呢？
![image](https://user-images.githubusercontent.com/30570735/158172862-1c855424-961d-4f01-9502-929fdf838197.png)
(quiz2的)

![image](https://user-images.githubusercontent.com/30570735/158171436-354c2b2e-15e0-4fb7-9eb8-b2f78269557e.png)
(quiz3的)

　3.可以麻煩助教把上次上課的投影片會上傳到E3上嗎？

　謝謝助教。

**Comment by ianchen0119** [comment]
同學您好：


1\. 關於：
> quiz3 q1是要找出密鑰長度並輸出，q2要解密輸出明文。而q2要解密也同樣需要先算出密鑰長度，又看到助教說兩個程式input 都只有密文，那這樣q2的程式內容是不是就要先重複一次q1的程式內容，找出密鑰長度後再繼續解密？
> 因為q2重複做了和q1一樣的事情所以有點疑惑。

老師的原意比較像是希望同學以 q1 的答案為基礎做出 q2 的答案，你可以重複內容或是使用變數指定 Key length 的長度，至於同學如何實作，只要在你的作業答案中補充即可，助教會去檢驗程式的功能是否正確。

2\. Quiz3 的圖應該是老師提出可以使用 I.C 的內積去求 Key 的偏移量。

3\. 剛剛已經上傳投影片至 E3 了，有任何問題可以在留言區提出。


謝謝！

**Comment by TzuMinYang** [comment]
助教您好：

　1.了解

　2-1.請問IC的內積算出來是代表什麼？為什麼可以利用他最大的值發生在哪個偏移量去求key的偏移量呢？

　2-2.這一行就是IC的內積嗎？
![image](https://user-images.githubusercontent.com/30570735/158323079-83085d11-72b8-413c-a9cb-833e4080c82d.png)

　2-3.是一個group的解密後明文中A-Z的頻率去和英文統計出來A-Z的頻率去做內積嗎？

　2-4.請問N'是指甚麼呢？

　2-5.請問這邊是不是有誤？
![image](https://user-images.githubusercontent.com/30570735/158323028-560ccf0a-9ef2-486f-81cb-4dee50307dee.png)

　3.了解

　謝謝助教。

**Comment by TrashBoatDora** [comment]
助教您好：
       想請問助教能不能講解一下IC內積是甚麼意思，能舉個例子講解一下怎麼做IC內積嗎?

謝謝助教。

**Comment by ianchen0119** [comment]
@TzuMinYang & @TrashBoatDora 
同學您好，你可以假設 K 為 0 - 25，然後套用公式去算當 K 為多少時可以得到最大的 I.C，這樣就可以得知該 Group 是以密鑰 'A' + K 去做加密的，原理的話可以參考老師投影片中附上的 A-Z 頻率分佈與凱撒密碼的關係。
（當然，這也不是唯一的解法，如果仔細觀察字母出現的頻率分佈，我們也可以利用母音的出現次數做比較⋯）

**Comment by ianchen0119** [comment]
@TzuMinYang 

再跟同學補充一下您的問題：
2-2
對
2-3 
同學可以去找一篇明文作為參考明文，公式就是將密文的其中一個 Group 與參考明文下去做運算。
2-4
N' 是參考明文的字元總數
2-5
我認為這個公式應該是老師不小心打錯了

**Comment by TrashBoatDora** [comment]
> 

助教不好意思我還是不太明白怎麼求出key，我已經在第一題透過計算IC得知正確的KEY LENGTH了，但在第二題找KEY的部分仍遲遲沒有下手點，試著用頻率去推算感覺是推出錯的答案，能請助教實際舉個算的例子怎麼推KEY跟怎麼使用IC去找嗎?謝謝!

**Comment by TzuMinYang** [comment]
助教您好：

　1.想確認fi+k'是密文的一個group+k解密後的明文A-Z出現的次數嗎？

　2.請問IC的內積為什麼是這個式子呢？請問是如何推導出來的？

　因為我查到的是說
![image](https://user-images.githubusercontent.com/30570735/158388769-a9fe090c-2956-420e-9f91-4ecd432f552e.png)
或
![image](https://user-images.githubusercontent.com/30570735/158389129-87d842fb-b9ff-4230-a5b0-c1e8debab3b3.png)

　都是直接計算最下面這段
![image](https://user-images.githubusercontent.com/30570735/158389222-071d27d2-12c1-4c06-a955-f4e182216a24.png)

　我可以理解計算最下面那段的意義，但我查不太到第一行IC內積那段公式。我想說要用密文的一個group+k解密後計算IC的公式和一篇參考明文計算IC的公式去內積，但推不出來到第一行IC內積那段公式，所以想請問是如何推導的？
![image](https://user-images.githubusercontent.com/30570735/158390683-eb6ce57c-1fcf-4be7-880c-451a5ab57d83.png)



　3.請問2-5抓到錯有bonus嗎？因為我看另一個issue抓到錯有bonus。

　謝謝助教。

**Comment by ianchen0119** [comment]
@TzuMinYang 

同學您好，

1. fi+k' 代表參考明文的字元 (i+k) 的出現頻率。

2. 嚴格來說這也不算是內積，老師給的公式只是要去求密文跟參考明文偏移到哪一個點時所求得的 I.C 是最大的，那時的偏移量 + 字母 A `chr(65 + shift)` 就代表 Key 的內容。

3. 我有跟老師反應，建議同學可以在週四課堂上跟老師詢問一下，如果沒問題我這邊會幫你做註記。

謝謝。

**Comment by ianchen0119** [comment]
@TrashBoatDora 

同學您好，

你可以先嘗試繪製出每個 Group 的字元頻率分佈圖，然後再對照老師課堂投影片附上的明文字元出現頻率（圖片在提及凱撒密碼的那一頁），如果用這個方式推導出幾個密碼的字元後，應該就可以嘗試其他更快速的方式求解。
此外，我覺得 @TzuMinYang 同學的提問蠻仔細的，你可以參考他的問題梳理一下想法。

如果還有什麼地方不清楚的話，可以再提出，
謝謝！

**Comment by ianchen0119** [comment]
@TzuMinYang 

同學您好，

老師已經同意你在 2-5 提出的加分請求，再麻煩你幫我留一下學號，謝謝！

**Comment by TzuMinYang** [comment]
助教您好：

　1.了解。

　2.我對第一行公式有個想法，但不確定是不是正確的，第一行是把「參考明文和密文的一個group偏移後的結果」合在一起當作一個整體，對這個整體去計算IC。請問這樣理解正確嗎？

　3.我的學號是0816147，謝謝。

　謝謝助教。

**Comment by ianchen0119** [comment]
@TzuMinYang 同學您好，

你的想法是可行的，可以寫程式去驗證看看。

謝謝！

**Comment by TrashBoatDora** [comment]
@ianchen0119 助教您好，
已經回答得非常清楚了，現在已經都明白了，謝謝!
