### ISSUE TITLE
Quiz4

### ISSUE THREAD

**Issue by taylor-wu96** [ianchen0119/Cryptography-Engineering-2022-spring#8]
想請問，計算一行的probability是不是要各自的條件機率相加呢？probability
另外如果遇到舉例 P(DRE|DR)但是P(DRE)=0 P(DR)=0 0分之0的狀況是無法相除的該怎麼計算呢？

**Comment by ianchen0119** [comment]
@a0716116z 
同學您好，
針對您的問題：
1\. 是
2\. 直接帶 0 應該也能得到正解

**Comment by ianchen0119** [comment]
同學您好，

為了避免其他同學提出相似的疑問，我先打開你的 Issue 直到作業繳交截止後再幫你關閉，謝謝！
