### ISSUE TITLE
Quiz 3 程式輸入問題

### ISSUE THREAD

**Issue by denny3388** [ianchen0119/Cryptography-Engineering-2022-spring#9]
請問助教～在測試的時候，輸入會是檔名還是檔案裡面的內容呢？

**Comment by ianchen0119** [comment]
@denny3388 
同學您好，
1\. 檔案的用途是存放你得到的明文而非密文。
2\. 測試時會將密文以 stdin 輸入並對比 stdout 的結果是否與答案相同。

謝謝！
